name: api-visualizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  PUBLISH-FE:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: registry.datexis.com/ksachs/api-visualizer:latest
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSPHRASE }}
          registry: registry.datexis.com
          snapshot: true
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Restart api-visualizer pod
        run: kubectl -n sachs delete pod -l app=api-visualizer
